# Generated by Django 4.2.6 on 2023-10-14 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('t_link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='country',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='나라'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='tasks',
            field=models.ManyToManyField(to='t_link.task', verbose_name='작업'),
        ),
        migrations.AddField(
            model_name='profile',
            name='matched_with',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
