# Generated by Django 4.2.6 on 2023-10-14 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('t_link', '0002_jobposting_country_jobposting_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user2',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatroom',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='matched_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_link.profile'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_date', models.DateField(auto_now_add=True)),
                ('missionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missionary_matches', to='t_link.profile')),
                ('short_term_missionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_term_matches', to='t_link.profile')),
            ],
        ),
    ]
