# Generated by Django 4.2.6 on 2023-10-16 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('t_link', '0004_chatroom_last_message_chatroom_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='language',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='zoom',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zoom Level'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification Time'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Time'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='tasks',
            field=models.ManyToManyField(to='t_link.task', verbose_name='Tasks'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification Time'),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Time'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='match',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification Time'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='Message Content'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Time'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sent Time'),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification Time'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='availability',
            field=models.DateField(verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Time'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.TextField(blank=True, null=True, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.TextField(verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personality',
            field=models.CharField(max_length=255, verbose_name='Personality'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tasks',
            field=models.ManyToManyField(to='t_link.task', verbose_name='Tasks'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('short_term', 'Short Term Missionary'), ('long_term', 'General Missionary')], max_length=12, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification Time'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verification Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Task Code'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Task Name'),
        ),
    ]
