# Generated by Django 4.2.6 on 2023-10-17 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('t_link', '0005_remove_task_created_at_remove_task_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Task Description'),
            preserve_default=False,
        ),
    ]
